/** Reference data and the sample catalogue used by scripts/seed.ts. */

export const REGIONS: [code: string, ar: string, en: string, ur: string, cities: [ar: string, en: string, ur: string][]][] = [
  ["RUH", "منطقة الرياض", "Riyadh Region", "ریاض ریجن", [["الرياض", "Riyadh", "ریاض"], ["الخرج", "Al Kharj", "الخرج"], ["الدرعية", "Diriyah", "الدرعیہ"], ["المجمعة", "Al Majmaah", "المجمعہ"], ["الدوادمي", "Dawadmi", "الدوادمی"], ["الزلفي", "Az Zulfi", "الزلفی"], ["وادي الدواسر", "Wadi ad-Dawasir", "وادی الدواسر"]]],
  ["MAK", "منطقة مكة المكرمة", "Makkah Region", "مکہ مکرمہ ریجن", [["مكة المكرمة", "Makkah", "مکہ مکرمہ"], ["جدة", "Jeddah", "جدہ"], ["الطائف", "Taif", "طائف"], ["رابغ", "Rabigh", "رابغ"], ["القنفذة", "Al Qunfudhah", "القنفذہ"]]],
  ["MED", "منطقة المدينة المنورة", "Madinah Region", "مدینہ منورہ ریجن", [["المدينة المنورة", "Madinah", "مدینہ منورہ"], ["ينبع", "Yanbu", "ینبع"], ["العلا", "AlUla", "العلا"]]],
  ["QAS", "منطقة القصيم", "Qassim Region", "قصیم ریجن", [["بريدة", "Buraydah", "بریدہ"], ["عنيزة", "Unaizah", "عنیزہ"], ["الرس", "Ar Rass", "الرس"]]],
  ["EAS", "المنطقة الشرقية", "Eastern Province", "مشرقی صوبہ", [["الدمام", "Dammam", "دمام"], ["الخبر", "Khobar", "الخبر"], ["الظهران", "Dhahran", "ظہران"], ["الأحساء", "Al Ahsa", "الاحساء"], ["الجبيل", "Jubail", "الجبیل"], ["القطيف", "Qatif", "القطیف"], ["حفر الباطن", "Hafar Al-Batin", "حفر الباطن"], ["الخفجي", "Khafji", "الخفجی"]]],
  ["ASR", "منطقة عسير", "Asir Region", "عسیر ریجن", [["أبها", "Abha", "ابہا"], ["خميس مشيط", "Khamis Mushait", "خمیس مشیط"], ["بيشة", "Bisha", "بیشہ"], ["محايل عسير", "Muhayil Asir", "محایل عسیر"]]],
  ["TBK", "منطقة تبوك", "Tabuk Region", "تبوک ریجن", [["تبوك", "Tabuk", "تبوک"], ["ضباء", "Duba", "ضباء"]]],
  ["HAL", "منطقة حائل", "Hail Region", "حائل ریجن", [["حائل", "Hail", "حائل"]]],
  ["NBR", "منطقة الحدود الشمالية", "Northern Borders Region", "شمالی سرحدی ریجن", [["عرعر", "Arar", "عرعر"], ["رفحاء", "Rafha", "رفحاء"], ["طريف", "Turaif", "طریف"]]],
  ["JAZ", "منطقة جازان", "Jazan Region", "جازان ریجن", [["جازان", "Jazan", "جازان"], ["صبيا", "Sabya", "صبیا"], ["أبو عريش", "Abu Arish", "ابو عریش"]]],
  ["NAJ", "منطقة نجران", "Najran Region", "نجران ریجن", [["نجران", "Najran", "نجران"], ["شرورة", "Sharurah", "شرورہ"]]],
  ["BAH", "منطقة الباحة", "Al Bahah Region", "الباحہ ریجن", [["الباحة", "Al Bahah", "الباحہ"], ["بلجرشي", "Baljurashi", "بلجرشی"]]],
  ["JOF", "منطقة الجوف", "Al Jawf Region", "الجوف ریجن", [["سكاكا", "Sakaka", "سکاکا"], ["دومة الجندل", "Dumat al-Jandal", "دومۃ الجندل"], ["القريات", "Qurayyat", "القریات"]]],
];

export const CATEGORIES: [slug: string, icon: string, ar: string, en: string, ur: string, parent?: string][] = [
  ["switches", "switch", "المفاتيح الكهربائية", "Electrical switches", "برقی سوئچز"],
  ["sockets", "socket", "الأفياش والمقابس", "Electrical sockets", "برقی ساکٹس"],
  ["led-lights", "led", "إنارة LED", "LED lights", "ایل ای ڈی لائٹس"],
  ["bulbs", "bulb", "اللمبات", "Bulbs", "بلب"],
  ["ceiling-lights", "ceiling", "إنارة الأسقف", "Ceiling lights", "چھت کی لائٹس"],
  ["downlights", "downlight", "سبوت لايت", "Downlights", "ڈاؤن لائٹس"],
  ["flood-lights", "flood", "الكشافات", "Flood lights", "فلڈ لائٹس"],
  ["outdoor-lights", "outdoor", "الإنارة الخارجية", "Outdoor lights", "بیرونی لائٹس"],
  ["wires-cables", "cable", "الأسلاك والكابلات", "Wires and cables", "تاریں اور کیبلز"],
  ["breakers", "breaker", "القواطع الكهربائية", "Circuit breakers", "سرکٹ بریکرز"],
  ["distribution-boards", "board", "لوحات التوزيع", "Distribution boards", "ڈسٹری بیوشن بورڈز"],
  ["contactors", "contactor", "الكونتاكتورات", "Contactors", "کنٹیکٹرز"],
  ["relays", "relay", "الريليهات", "Relays", "ریلے"],
  ["accessories", "accessory", "الإكسسوارات الكهربائية", "Electrical accessories", "برقی لوازمات"],
  ["extension-boards", "extension", "التوصيلات والمشتركات", "Extension boards", "ایکسٹینشن بورڈز"],
  ["plugs", "plug", "القوابس", "Plugs", "پلگ"],
  ["fans", "fan", "المراوح", "Fans", "پنکھے"],
  ["tools", "tool", "العدد والأدوات الكهربائية", "Electrical tools", "برقی اوزار"],
  ["safety", "safety", "معدات السلامة", "Safety equipment", "حفاظتی سامان"],
  ["smart", "smart", "المنتجات الكهربائية الذكية", "Smart electrical products", "سمارٹ برقی مصنوعات"],
  ["other", "other", "منتجات كهربائية أخرى", "Other electrical products", "دیگر برقی مصنوعات"],
  // sub-categories (the tree can be extended to any depth from the admin panel)
  ["mcb", "breaker", "قواطع MCB", "Miniature circuit breakers (MCB)", "ایم سی بی بریکرز", "breakers"],
  ["rccb", "breaker", "قواطع التسريب الأرضي", "Residual current devices (RCCB)", "آر سی سی بی بریکرز", "breakers"],
  ["building-wires", "cable", "أسلاك المباني", "Building wires", "عمارتی تاریں", "wires-cables"],
  ["flexible-cables", "cable", "الكابلات المرنة", "Flexible cables", "لچکدار کیبلز", "wires-cables"],
];

export const BRANDS: [slug: string, ar: string, en: string, ur: string, popular: boolean][] = [
  ["schneider-electric", "شنايدر إلكتريك", "Schneider Electric", "شنائیڈر الیکٹرک", true],
  ["abb", "إيه بي بي", "ABB", "اے بی بی", true],
  ["legrand", "ليجراند", "Legrand", "لیگرانڈ", true],
  ["philips", "فيليبس", "Philips", "فلپس", true],
  ["panasonic", "باناسونيك", "Panasonic", "پیناسونک", true],
  ["alfanar", "الفنار", "alfanar", "الفنار", true],
  ["riyadh-cables", "كابلات الرياض", "Riyadh Cables", "ریاض کیبلز", true],
  ["stanley", "ستانلي", "Stanley", "اسٹینلے", false],
];

/** Specification labels: key → [ar, en, ur] */
export const SPEC_LABELS: Record<string, [string, string, string]> = {
  current: ["التيار المقنن", "Rated current", "ریٹڈ کرنٹ"],
  voltage: ["الجهد", "Voltage", "وولٹیج"],
  power: ["القدرة", "Power", "پاور"],
  poles: ["عدد الأقطاب", "Poles", "پولز"],
  curve: ["منحنى الفصل", "Trip curve", "ٹرپ کَرو"],
  breaking: ["قدرة القطع", "Breaking capacity", "بریکنگ کپیسٹی"],
  sensitivity: ["حساسية التسريب", "Sensitivity", "حساسیت"],
  ip: ["درجة الحماية", "Protection rating", "تحفظ کی درجہ بندی"],
  cct: ["لون الإضاءة", "Colour temperature", "روشنی کا رنگ"],
  lumen: ["شدة الإضاءة", "Luminous flux", "روشنی کی مقدار"],
  base: ["نوع القاعدة", "Lamp base", "بلب بیس"],
  size: ["المقاس", "Size", "سائز"],
  section: ["مقطع الموصل", "Conductor size", "کنڈکٹر سائز"],
  length: ["الطول", "Length", "لمبائی"],
  cores: ["عدد الموصلات", "Cores", "کورز"],
  material: ["المادة", "Material", "میٹریل"],
  gangs: ["عدد المفاتيح", "Gangs", "گینگ"],
  ways: ["عدد الخطوط", "Ways", "ویز"],
  outlets: ["عدد المخارج", "Outlets", "آؤٹ لیٹس"],
  coil: ["جهد الملف", "Coil voltage", "کوائل وولٹیج"],
  color: ["اللون", "Colour", "رنگ"],
  standard: ["المواصفة", "Standard", "معیار"],
  connectivity: ["الاتصال", "Connectivity", "کنیکٹیویٹی"],
  cutout: ["فتحة التركيب", "Cut-out", "کٹ آؤٹ"],
  sweep: ["قطر المروحة", "Sweep", "سویپ"],
  type: ["النوع", "Type", "قسم"],
};

export interface SeedProduct {
  sku: string; cat: string; brand: string | null; ar: string; en: string; ur: string;
  price: number; sale?: number; cost: number; stock: number; flags?: string; warranty?: number;
  specs: [key: string, value: string][];
}

/** Prices are in SAR including VAT and are sample values only — replace with your real catalogue. */
export const PRODUCTS: SeedProduct[] = [
  { sku: "SW-1G1W-WH", cat: "switches", brand: "schneider-electric", ar: "مفتاح إنارة مفرد اتجاه واحد 10 أمبير أبيض", en: "1-gang 1-way light switch 10A, white", ur: "سنگل گینگ ون وے لائٹ سوئچ 10 ایمپیئر، سفید", price: 18.5, cost: 10.2, stock: 240, flags: "best", warranty: 24, specs: [["current", "10A"], ["voltage", "250V"], ["gangs", "1"], ["color", "White"], ["standard", "BS 3676"]] },
  { sku: "SW-2G2W-WH", cat: "switches", brand: "schneider-electric", ar: "مفتاح إنارة مزدوج اتجاهين 10 أمبير أبيض", en: "2-gang 2-way light switch 10A, white", ur: "ڈبل گینگ ٹو وے لائٹ سوئچ 10 ایمپیئر، سفید", price: 29, cost: 16.5, stock: 180, warranty: 24, specs: [["current", "10A"], ["voltage", "250V"], ["gangs", "2"], ["color", "White"]] },
  { sku: "SW-3G1W-WH", cat: "switches", brand: "legrand", ar: "مفتاح إنارة ثلاثي اتجاه واحد 10 أمبير", en: "3-gang 1-way light switch 10A", ur: "تھری گینگ ون وے لائٹ سوئچ 10 ایمپیئر", price: 36, sale: 31, cost: 19.8, stock: 95, specs: [["current", "10A"], ["voltage", "250V"], ["gangs", "3"]] },
  { sku: "SW-DP45-WH", cat: "switches", brand: "abb", ar: "مفتاح سخان مزدوج القطب 45 أمبير مع لمبة بيان", en: "45A double-pole water heater switch with neon", ur: "45 ایمپیئر ڈبل پول واٹر ہیٹر سوئچ نیون کے ساتھ", price: 42, cost: 24, stock: 70, flags: "featured", warranty: 24, specs: [["current", "45A"], ["voltage", "250V"], ["poles", "2P"]] },
  { sku: "SK-13A-1G", cat: "sockets", brand: "schneider-electric", ar: "فيش ثلاثي مفرد 13 أمبير مع مفتاح", en: "13A single switched socket (Type G)", ur: "13 ایمپیئر سنگل سوئچڈ ساکٹ (ٹائپ جی)", price: 24, cost: 13.4, stock: 320, flags: "best,featured", warranty: 24, specs: [["current", "13A"], ["voltage", "250V"], ["gangs", "1"], ["standard", "BS 1363"]] },
  { sku: "SK-13A-2G", cat: "sockets", brand: "schneider-electric", ar: "فيش ثلاثي مزدوج 13 أمبير مع مفاتيح", en: "13A twin switched socket (Type G)", ur: "13 ایمپیئر ڈبل سوئچڈ ساکٹ (ٹائپ جی)", price: 39, cost: 22, stock: 210, warranty: 24, specs: [["current", "13A"], ["voltage", "250V"], ["gangs", "2"], ["standard", "BS 1363"]] },
  { sku: "SK-13A-USB", cat: "sockets", brand: "legrand", ar: "فيش 13 أمبير مع منفذي USB للشحن", en: "13A socket with 2 USB charging ports", ur: "13 ایمپیئر ساکٹ 2 یو ایس بی چارجنگ پورٹس کے ساتھ", price: 79, sale: 69, cost: 44, stock: 60, flags: "new", warranty: 24, specs: [["current", "13A"], ["voltage", "250V"], ["type", "USB 2.4A"]] },
  { sku: "SK-WP-IP66", cat: "sockets", brand: "abb", ar: "فيش خارجي مقاوم للماء 13 أمبير IP66", en: "Weatherproof outdoor socket 13A IP66", ur: "واٹر پروف بیرونی ساکٹ 13 ایمپیئر IP66", price: 96, cost: 58, stock: 34, specs: [["current", "13A"], ["voltage", "250V"], ["ip", "IP66"]] },
  { sku: "LED-PNL-6060", cat: "led-lights", brand: "philips", ar: "لوحة LED 60×60 سم 40 واط إضاءة بيضاء", en: "LED panel 60×60 cm 40W cool white", ur: "ایل ای ڈی پینل 60×60 سینٹی میٹر 40 واٹ ٹھنڈی سفید", price: 115, sale: 98, cost: 66, stock: 85, flags: "featured,best", warranty: 24, specs: [["power", "40W"], ["cct", "6500K"], ["lumen", "4000 lm"], ["size", "60×60 cm"]] },
  { sku: "LED-STRIP-5M", cat: "led-lights", brand: null, ar: "شريط إضاءة LED 5 متر مع محول 12 فولت", en: "LED strip light 5 m with 12V driver", ur: "ایل ای ڈی اسٹرپ لائٹ 5 میٹر 12 وولٹ ڈرائیور کے ساتھ", price: 69, cost: 35, stock: 140, flags: "new", warranty: 12, specs: [["power", "60W"], ["voltage", "12V"], ["length", "5 m"], ["cct", "3000K"]] },
  { sku: "LED-BATTEN-120", cat: "led-lights", brand: "philips", ar: "لمبة LED طولية 120 سم 36 واط", en: "LED batten 120 cm 36W", ur: "ایل ای ڈی بیٹن 120 سینٹی میٹر 36 واٹ", price: 45, cost: 26, stock: 200, warranty: 24, specs: [["power", "36W"], ["cct", "6500K"], ["lumen", "3600 lm"], ["length", "120 cm"]] },
  { sku: "BLB-E27-9W-WW", cat: "bulbs", brand: "philips", ar: "لمبة LED 9 واط قاعدة E27 إضاءة دافئة", en: "LED bulb 9W E27 warm white", ur: "ایل ای ڈی بلب 9 واٹ E27 وارم وائٹ", price: 9.5, cost: 5.1, stock: 600, flags: "best", warranty: 12, specs: [["power", "9W"], ["base", "E27"], ["cct", "3000K"], ["lumen", "806 lm"]] },
  { sku: "BLB-E27-12W-CW", cat: "bulbs", brand: "philips", ar: "لمبة LED 12 واط قاعدة E27 إضاءة بيضاء", en: "LED bulb 12W E27 cool white", ur: "ایل ای ڈی بلب 12 واٹ E27 کول وائٹ", price: 12, cost: 6.8, stock: 520, warranty: 12, specs: [["power", "12W"], ["base", "E27"], ["cct", "6500K"], ["lumen", "1100 lm"]] },
  { sku: "BLB-E14-5W-CDL", cat: "bulbs", brand: "panasonic", ar: "لمبة شمعة LED 5 واط قاعدة E14", en: "LED candle bulb 5W E14", ur: "ایل ای ڈی کینڈل بلب 5 واٹ E14", price: 8, cost: 4.2, stock: 300, specs: [["power", "5W"], ["base", "E14"], ["cct", "3000K"]] },
  { sku: "CL-RND-24W", cat: "ceiling-lights", brand: "panasonic", ar: "إنارة سقف دائرية LED 24 واط", en: "Round LED ceiling light 24W", ur: "گول ایل ای ڈی سیلنگ لائٹ 24 واٹ", price: 89, cost: 52, stock: 48, flags: "featured", warranty: 24, specs: [["power", "24W"], ["cct", "4000K"], ["size", "38 cm"], ["ip", "IP20"]] },
  { sku: "CL-SQ-36W-3C", cat: "ceiling-lights", brand: "panasonic", ar: "إنارة سقف مربعة LED 36 واط ثلاث ألوان", en: "Square LED ceiling light 36W, 3 colour modes", ur: "مربع ایل ای ڈی سیلنگ لائٹ 36 واٹ، تین رنگ", price: 139, sale: 119, cost: 80, stock: 26, flags: "new", warranty: 24, specs: [["power", "36W"], ["cct", "3000–6500K"], ["size", "45×45 cm"]] },
  { sku: "DL-7W-WW", cat: "downlights", brand: "philips", ar: "سبوت لايت LED غاطس 7 واط إضاءة دافئة", en: "Recessed LED downlight 7W warm white", ur: "ریسیسڈ ایل ای ڈی ڈاؤن لائٹ 7 واٹ وارم وائٹ", price: 14.5, cost: 7.9, stock: 800, flags: "best", warranty: 24, specs: [["power", "7W"], ["cct", "3000K"], ["cutout", "75 mm"], ["lumen", "600 lm"]] },
  { sku: "DL-12W-CW", cat: "downlights", brand: "philips", ar: "سبوت لايت LED غاطس 12 واط إضاءة بيضاء", en: "Recessed LED downlight 12W cool white", ur: "ریسیسڈ ایل ای ڈی ڈاؤن لائٹ 12 واٹ کول وائٹ", price: 19, cost: 10.6, stock: 640, warranty: 24, specs: [["power", "12W"], ["cct", "6500K"], ["cutout", "100 mm"], ["lumen", "1050 lm"]] },
  { sku: "DL-TRK-20W", cat: "downlights", brand: null, ar: "سبوت تراك LED 20 واط أسود", en: "LED track spotlight 20W, black", ur: "ایل ای ڈی ٹریک اسپاٹ لائٹ 20 واٹ، سیاہ", price: 55, cost: 31, stock: 0, warranty: 12, specs: [["power", "20W"], ["cct", "4000K"], ["color", "Black"]] },
  { sku: "FL-50W-IP65", cat: "flood-lights", brand: "philips", ar: "كشاف LED 50 واط خارجي IP65", en: "LED flood light 50W IP65", ur: "ایل ای ڈی فلڈ لائٹ 50 واٹ IP65", price: 75, cost: 43, stock: 110, flags: "best", warranty: 24, specs: [["power", "50W"], ["ip", "IP65"], ["cct", "6500K"], ["lumen", "4500 lm"]] },
  { sku: "FL-100W-IP65", cat: "flood-lights", brand: "philips", ar: "كشاف LED 100 واط خارجي IP65", en: "LED flood light 100W IP65", ur: "ایل ای ڈی فلڈ لائٹ 100 واٹ IP65", price: 135, sale: 118, cost: 79, stock: 64, warranty: 24, specs: [["power", "100W"], ["ip", "IP65"], ["cct", "6500K"], ["lumen", "9000 lm"]] },
  { sku: "FL-SOLAR-60W", cat: "flood-lights", brand: null, ar: "كشاف طاقة شمسية 60 واط مع ريموت", en: "Solar flood light 60W with remote", ur: "سولر فلڈ لائٹ 60 واٹ ریموٹ کے ساتھ", price: 99, cost: 55, stock: 4, flags: "new", warranty: 12, specs: [["power", "60W"], ["ip", "IP67"], ["type", "Solar"]] },
  { sku: "OL-WALL-UD", cat: "outdoor-lights", brand: "panasonic", ar: "إنارة جدارية خارجية اتجاهين IP54", en: "Outdoor up/down wall light IP54", ur: "بیرونی اپ/ڈاؤن وال لائٹ IP54", price: 65, cost: 37, stock: 72, warranty: 12, specs: [["power", "10W"], ["ip", "IP54"], ["cct", "3000K"]] },
  { sku: "OL-BOLLARD-60", cat: "outdoor-lights", brand: null, ar: "عمود إنارة حدائق 60 سم", en: "Garden bollard light 60 cm", ur: "گارڈن بولارڈ لائٹ 60 سینٹی میٹر", price: 149, cost: 92, stock: 18, warranty: 12, specs: [["base", "E27"], ["ip", "IP65"], ["size", "60 cm"]] },
  { sku: "CBL-1C-2.5-RD", cat: "building-wires", brand: "riyadh-cables", ar: "سلك نحاس مفرد 2.5 ملم أحمر لفة 100 ياردة", en: "Single-core copper wire 2.5 mm² red, 100 yd coil", ur: "سنگل کور کاپر وائر 2.5 ملی میٹر سرخ، 100 گز کوائل", price: 132, cost: 104, stock: 150, flags: "best,featured", specs: [["section", "2.5 mm²"], ["voltage", "450/750V"], ["length", "100 yd"], ["material", "Copper / PVC"]] },
  { sku: "CBL-1C-4-BK", cat: "building-wires", brand: "riyadh-cables", ar: "سلك نحاس مفرد 4 ملم أسود لفة 100 ياردة", en: "Single-core copper wire 4 mm² black, 100 yd coil", ur: "سنگل کور کاپر وائر 4 ملی میٹر سیاہ، 100 گز کوائل", price: 205, cost: 166, stock: 90, specs: [["section", "4 mm²"], ["voltage", "450/750V"], ["length", "100 yd"], ["material", "Copper / PVC"]] },
  { sku: "CBL-1C-6-GY", cat: "building-wires", brand: "riyadh-cables", ar: "سلك نحاس مفرد 6 ملم أخضر/أصفر (أرضي) لفة 100 ياردة", en: "Single-core copper wire 6 mm² green/yellow (earth), 100 yd coil", ur: "سنگل کور کاپر وائر 6 ملی میٹر سبز/پیلا (ارتھ)، 100 گز", price: 298, cost: 244, stock: 55, specs: [["section", "6 mm²"], ["voltage", "450/750V"], ["length", "100 yd"]] },
  { sku: "CBL-3C-2.5-FLX", cat: "flexible-cables", brand: "riyadh-cables", ar: "كابل مرن 3×2.5 ملم لفة 50 متر", en: "Flexible cable 3×2.5 mm², 50 m coil", ur: "فلیکسیبل کیبل 3×2.5 ملی میٹر، 50 میٹر کوائل", price: 285, sale: 259, cost: 215, stock: 40, specs: [["section", "3×2.5 mm²"], ["cores", "3"], ["length", "50 m"], ["voltage", "300/500V"]] },
  { sku: "MCB-1P-16-C", cat: "mcb", brand: "schneider-electric", ar: "قاطع MCB قطب واحد 16 أمبير منحنى C", en: "MCB 1-pole 16A C-curve", ur: "ایم سی بی سنگل پول 16 ایمپیئر سی کَرو", price: 21, cost: 12.4, stock: 400, flags: "best,featured", warranty: 24, specs: [["current", "16A"], ["poles", "1P"], ["curve", "C"], ["breaking", "6 kA"], ["standard", "IEC 60898-1"]] },
  { sku: "MCB-1P-20-C", cat: "mcb", brand: "schneider-electric", ar: "قاطع MCB قطب واحد 20 أمبير منحنى C", en: "MCB 1-pole 20A C-curve", ur: "ایم سی بی سنگل پول 20 ایمپیئر سی کَرو", price: 21, cost: 12.4, stock: 350, warranty: 24, specs: [["current", "20A"], ["poles", "1P"], ["curve", "C"], ["breaking", "6 kA"]] },
  { sku: "MCB-3P-32-C", cat: "mcb", brand: "abb", ar: "قاطع MCB ثلاثي الأقطاب 32 أمبير منحنى C", en: "MCB 3-pole 32A C-curve", ur: "ایم سی بی تھری پول 32 ایمپیئر سی کَرو", price: 84, cost: 52, stock: 120, warranty: 24, specs: [["current", "32A"], ["poles", "3P"], ["curve", "C"], ["breaking", "6 kA"]] },
  { sku: "RCCB-2P-40-30", cat: "rccb", brand: "schneider-electric", ar: "قاطع تسريب أرضي قطبين 40 أمبير 30 ملي أمبير", en: "RCCB 2-pole 40A 30 mA", ur: "آر سی سی بی ڈبل پول 40 ایمپیئر 30 ملی ایمپیئر", price: 139, sale: 125, cost: 88, stock: 75, flags: "featured", warranty: 24, specs: [["current", "40A"], ["poles", "2P"], ["sensitivity", "30 mA"], ["type", "AC"], ["standard", "IEC 61008-1"]] },
  { sku: "RCCB-4P-63-30", cat: "rccb", brand: "abb", ar: "قاطع تسريب أرضي أربعة أقطاب 63 أمبير 30 ملي أمبير", en: "RCCB 4-pole 63A 30 mA", ur: "آر سی سی بی فور پول 63 ایمپیئر 30 ملی ایمپیئر", price: 265, cost: 178, stock: 3, warranty: 24, specs: [["current", "63A"], ["poles", "4P"], ["sensitivity", "30 mA"]] },
  { sku: "DB-12W-FL", cat: "distribution-boards", brand: "alfanar", ar: "لوحة توزيع 12 خط غاطسة مع باب", en: "12-way flush distribution board with door", ur: "12 وے فلش ڈسٹری بیوشن بورڈ دروازے کے ساتھ", price: 165, cost: 108, stock: 42, flags: "featured", warranty: 24, specs: [["ways", "12"], ["type", "Flush"], ["ip", "IP40"], ["material", "Steel"]] },
  { sku: "DB-24W-SF", cat: "distribution-boards", brand: "alfanar", ar: "لوحة توزيع 24 خط ظاهرة", en: "24-way surface distribution board", ur: "24 وے سرفیس ڈسٹری بیوشن بورڈ", price: 289, cost: 196, stock: 16, warranty: 24, specs: [["ways", "24"], ["type", "Surface"], ["ip", "IP40"], ["material", "Steel"]] },
  { sku: "CT-3P-25-220", cat: "contactors", brand: "schneider-electric", ar: "كونتاكتور ثلاثي 25 أمبير ملف 220 فولت", en: "3-pole contactor 25A, 220V coil", ur: "تھری پول کنٹیکٹر 25 ایمپیئر، 220 وولٹ کوائل", price: 118, cost: 76, stock: 58, warranty: 12, specs: [["current", "25A"], ["poles", "3P"], ["coil", "220V AC"], ["type", "AC-3"]] },
  { sku: "CT-3P-40-220", cat: "contactors", brand: "abb", ar: "كونتاكتور ثلاثي 40 أمبير ملف 220 فولت", en: "3-pole contactor 40A, 220V coil", ur: "تھری پول کنٹیکٹر 40 ایمپیئر، 220 وولٹ کوائل", price: 189, cost: 124, stock: 22, warranty: 12, specs: [["current", "40A"], ["poles", "3P"], ["coil", "220V AC"]] },
  { sku: "RL-8P-220", cat: "relays", brand: "schneider-electric", ar: "ريليه 8 أطراف ملف 220 فولت مع قاعدة", en: "8-pin relay 220V coil with base", ur: "8 پن ریلے 220 وولٹ کوائل بیس کے ساتھ", price: 34, cost: 19.5, stock: 130, specs: [["coil", "220V AC"], ["current", "10A"], ["type", "DPDT"]] },
  { sku: "RL-OL-9-13", cat: "relays", brand: "abb", ar: "ريليه حماية حراري (أوفرلود) 9–13 أمبير", en: "Thermal overload relay 9–13A", ur: "تھرمل اوورلوڈ ریلے 9–13 ایمپیئر", price: 96, cost: 61, stock: 30, specs: [["current", "9–13A"], ["type", "Thermal"]] },
  { sku: "ACC-TAPE-BK", cat: "accessories", brand: null, ar: "شريط عازل كهربائي أسود 19 ملم × 18 متر", en: "PVC insulation tape black 19 mm × 18 m", ur: "پی وی سی انسولیشن ٹیپ سیاہ 19 ملی میٹر × 18 میٹر", price: 4.5, cost: 2.1, stock: 1200, flags: "best", specs: [["size", "19 mm × 18 m"], ["voltage", "600V"], ["color", "Black"]] },
  { sku: "ACC-BOX-3X3", cat: "accessories", brand: null, ar: "علبة مفاتيح غاطسة 3×3 بلاستيك", en: "3×3 flush mounting box, PVC", ur: "3×3 فلش ماؤنٹنگ باکس، پی وی سی", price: 2.5, cost: 1.1, stock: 2500, specs: [["size", "3×3 in"], ["material", "PVC"]] },
  { sku: "ACC-TIES-200", cat: "accessories", brand: null, ar: "أربطة كابلات 200 ملم (100 حبة)", en: "Cable ties 200 mm (pack of 100)", ur: "کیبل ٹائیز 200 ملی میٹر (100 عدد)", price: 9, cost: 4.4, stock: 380, specs: [["length", "200 mm"], ["material", "Nylon 66"]] },
  { sku: "EXT-4W-3M", cat: "extension-boards", brand: "panasonic", ar: "توصيلة كهربائية 4 مخارج 3 متر مع مفتاح", en: "4-way extension board 3 m with switch", ur: "4 وے ایکسٹینشن بورڈ 3 میٹر سوئچ کے ساتھ", price: 45, cost: 27, stock: 160, flags: "best", warranty: 12, specs: [["outlets", "4"], ["current", "13A"], ["length", "3 m"]] },
  { sku: "EXT-6W-5M-SP", cat: "extension-boards", brand: "legrand", ar: "توصيلة 6 مخارج 5 متر مع حماية من ارتفاع التيار", en: "6-way surge-protected extension 5 m", ur: "6 وے سرج پروٹیکٹڈ ایکسٹینشن 5 میٹر", price: 89, sale: 79, cost: 54, stock: 66, flags: "new", warranty: 24, specs: [["outlets", "6"], ["current", "13A"], ["length", "5 m"], ["type", "Surge protected"]] },
  { sku: "PLG-13A-TOP", cat: "plugs", brand: null, ar: "فيش ثلاثي 13 أمبير مع فيوز", en: "13A fused plug top (Type G)", ur: "13 ایمپیئر فیوزڈ پلگ ٹاپ (ٹائپ جی)", price: 6, cost: 3, stock: 900, specs: [["current", "13A"], ["voltage", "250V"], ["standard", "BS 1363"]] },
  { sku: "PLG-IND-32A-5P", cat: "plugs", brand: "legrand", ar: "فيش صناعي 32 أمبير خمسة أطراف IP44", en: "Industrial plug 32A 5-pin IP44", ur: "انڈسٹریل پلگ 32 ایمپیئر 5 پن IP44", price: 58, cost: 35, stock: 44, specs: [["current", "32A"], ["voltage", "400V"], ["poles", "3P+N+E"], ["ip", "IP44"]] },
  { sku: "FAN-CEIL-56", cat: "fans", brand: "panasonic", ar: "مروحة سقف 56 بوصة ثلاث ريش", en: "Ceiling fan 56-inch, 3 blades", ur: "سیلنگ فین 56 انچ، 3 بلیڈ", price: 245, sale: 219, cost: 160, stock: 28, flags: "featured", warranty: 24, specs: [["sweep", "56 in"], ["power", "75W"], ["voltage", "220V"]] },
  { sku: "FAN-EXH-8", cat: "fans", brand: "panasonic", ar: "مروحة شفط 8 بوصة للحمامات", en: "Exhaust fan 8-inch for bathrooms", ur: "ایگزاسٹ فین 8 انچ باتھ روم کے لیے", price: 78, cost: 47, stock: 50, warranty: 12, specs: [["sweep", "8 in"], ["power", "25W"], ["voltage", "220V"]] },
  { sku: "TL-TESTER-SCR", cat: "tools", brand: "stanley", ar: "مفك اختبار كهرباء 100–500 فولت", en: "Voltage tester screwdriver 100–500V", ur: "وولٹیج ٹیسٹر اسکریو ڈرائیور 100–500 وولٹ", price: 9, cost: 4.5, stock: 260, specs: [["voltage", "100–500V"], ["length", "140 mm"]] },
  { sku: "TL-PLIER-8", cat: "tools", brand: "stanley", ar: "زرادية كهربائي معزولة 8 بوصة 1000 فولت", en: "Insulated combination pliers 8-inch 1000V", ur: "انسولیٹڈ کمبی نیشن پلاس 8 انچ 1000 وولٹ", price: 59, cost: 36, stock: 80, flags: "featured", specs: [["voltage", "1000V"], ["size", "8 in"], ["standard", "IEC 60900"]] },
  { sku: "TL-DMM-600", cat: "tools", brand: null, ar: "ملتيميتر رقمي 600 فولت", en: "Digital multimeter 600V", ur: "ڈیجیٹل ملٹی میٹر 600 وولٹ", price: 119, sale: 99, cost: 68, stock: 37, flags: "new", warranty: 12, specs: [["voltage", "600V"], ["current", "10A"], ["type", "CAT III"]] },
  { sku: "SF-GLOVE-CL0", cat: "safety", brand: null, ar: "قفازات عازلة للكهرباء فئة 0 حتى 1000 فولت", en: "Insulating gloves class 0, up to 1000V", ur: "انسولیٹنگ دستانے کلاس 0، 1000 وولٹ تک", price: 135, cost: 86, stock: 24, specs: [["voltage", "1000V"], ["type", "Class 0"], ["standard", "IEC 60903"]] },
  { sku: "SF-HELMET-YL", cat: "safety", brand: null, ar: "خوذة سلامة صفراء", en: "Safety helmet, yellow", ur: "سیفٹی ہیلمٹ، پیلا", price: 28, cost: 15, stock: 90, specs: [["color", "Yellow"], ["standard", "EN 397"]] },
  { sku: "SM-WIFI-SW-2G", cat: "smart", brand: null, ar: "مفتاح ذكي واي فاي لمس مزدوج", en: "Smart Wi-Fi touch switch, 2-gang", ur: "سمارٹ وائی فائی ٹچ سوئچ، ڈبل گینگ", price: 129, sale: 109, cost: 72, stock: 45, flags: "new,featured", warranty: 12, specs: [["gangs", "2"], ["connectivity", "Wi-Fi 2.4 GHz"], ["current", "10A"]] },
  { sku: "SM-PLUG-16A", cat: "smart", brand: null, ar: "فيش ذكي 16 أمبير مع قياس الاستهلاك", en: "Smart plug 16A with energy monitoring", ur: "سمارٹ پلگ 16 ایمپیئر توانائی مانیٹرنگ کے ساتھ", price: 69, cost: 39, stock: 88, flags: "new", warranty: 12, specs: [["current", "16A"], ["connectivity", "Wi-Fi 2.4 GHz"], ["voltage", "220V"]] },
  { sku: "OT-TIMER-24H", cat: "other", brand: "legrand", ar: "مؤقت ميكانيكي 24 ساعة 16 أمبير", en: "24-hour mechanical timer 16A", ur: "24 گھنٹے مکینیکل ٹائمر 16 ایمپیئر", price: 74, cost: 45, stock: 52, warranty: 12, specs: [["current", "16A"], ["voltage", "220V"], ["type", "DIN rail"]] },
  { sku: "OT-DOORBELL", cat: "other", brand: null, ar: "جرس باب لاسلكي", en: "Wireless doorbell", ur: "وائرلیس ڈور بیل", price: 49, cost: 26, stock: 61, warranty: 12, specs: [["type", "Wireless"], ["length", "150 m"]] },
];

export const DESCRIPTIONS: Record<string, [ar: string, en: string, ur: string]> = {
  default: [
    "{name}. منتج مطابق للمواصفات المذكورة في جدول المواصفات، مناسب للاستخدام السكني والتجاري. يُنصح بأن يتم التركيب على يد كهربائي مؤهل ووفق كود البناء السعودي للأعمال الكهربائية.",
    "{name}. Built to the ratings listed in the specifications table and suitable for residential and commercial use. Installation by a qualified electrician in line with the Saudi Building Code electrical requirements is recommended.",
    "{name}۔ یہ پروڈکٹ وضاحتی جدول میں درج ریٹنگز کے مطابق ہے اور رہائشی و تجارتی استعمال کے لیے موزوں ہے۔ تنصیب کسی مستند الیکٹریشن سے سعودی بلڈنگ کوڈ کے مطابق کروانے کی سفارش کی جاتی ہے۔",
  ],
};

export const SHIPPING_METHODS = [
  { key: "standard", name_ar: "توصيل عادي", name_en: "Standard delivery", name_ur: "عام ڈیلیوری", description_ar: "توصيل إلى باب المنزل خلال 2–5 أيام عمل", description_en: "Door-to-door delivery in 2–5 working days", description_ur: "2 سے 5 کاروباری دنوں میں گھر تک ڈیلیوری", base_fee: 2500, free_threshold: 30000, min_days: 2, max_days: 5, cod_allowed: true, is_pickup: false, sort: 1 },
  { key: "express", name_ar: "توصيل سريع", name_en: "Express delivery", name_ur: "ایکسپریس ڈیلیوری", description_ar: "توصيل خلال يوم إلى يومي عمل للمدن الرئيسية", description_en: "Delivery in 1–2 working days to major cities", description_ur: "بڑے شہروں میں 1 سے 2 کاروباری دنوں میں ڈیلیوری", base_fee: 4500, free_threshold: null, min_days: 1, max_days: 2, cod_allowed: true, is_pickup: false, sort: 2 },
  { key: "pickup", name_ar: "استلام من المعرض", name_en: "Pick up from the shop", name_ur: "دکان سے وصولی", description_ar: "جاهز للاستلام خلال يوم عمل واحد", description_en: "Ready for collection within one working day", description_ur: "ایک کاروباری دن میں وصولی کے لیے تیار", base_fee: 0, free_threshold: null, min_days: 0, max_days: 1, cod_allowed: true, is_pickup: true, sort: 3 },
];

export const HOME_SECTIONS: [type: string, ar: string, en: string, ur: string, limit: number][] = [
  ["hero", "", "", "", 8],
  ["categories", "تسوّق حسب القسم", "Shop by category", "زمرے کے لحاظ سے خریداری", 12],
  ["deals", "عروض وتخفيضات", "Offers and discounts", "پیشکشیں اور رعایتیں", 10],
  ["featured", "منتجات مختارة", "Featured products", "منتخب مصنوعات", 10],
  ["promo", "", "", "", 2],
  ["best_sellers", "الأكثر مبيعًا", "Best sellers", "سب سے زیادہ فروخت", 10],
  ["new_arrivals", "وصل حديثًا", "New arrivals", "نئی آمد", 10],
  ["brands", "علامات تجارية نوفرها", "Brands we stock", "ہمارے پاس دستیاب برانڈز", 12],
  ["reviews", "آراء العملاء", "Customer reviews", "گاہکوں کی آراء", 6],
  ["why_us", "لماذا جناح الريادة؟", "Why Janah Al Riyada?", "جناح الریادہ کیوں؟", 4],
  ["delivery", "التوصيل والدفع", "Delivery and payment", "ڈیلیوری اور ادائیگی", 4],
  ["contact", "تواصل معنا", "Contact us", "ہم سے رابطہ کریں", 1],
];

export const BANNERS = [
  { placement: "hero", title_ar: "كل ما تحتاجه لوحتك الكهربائية، من القاطع إلى السلك", title_en: "Everything your panel needs, from the breaker to the wire", title_ur: "آپ کے پینل کی ہر ضرورت، بریکر سے لے کر تار تک", subtitle_ar: "مفاتيح وأفياش وإنارة LED وكابلات وقواطع أصلية، بأسعار شاملة الضريبة وتوصيل لجميع مناطق المملكة.", subtitle_en: "Genuine switches, sockets, LED lighting, cables and breakers. Prices include VAT, with delivery to every region of the Kingdom.", subtitle_ur: "اصلی سوئچ، ساکٹ، ایل ای ڈی لائٹس، کیبلز اور بریکرز۔ قیمتوں میں VAT شامل ہے اور پورے سعودی عرب میں ڈیلیوری۔", cta_ar: "تصفّح جميع المنتجات", cta_en: "Browse all products", cta_ur: "تمام مصنوعات دیکھیں", link: "/products", sort: 1 },
  { placement: "promo", title_ar: "قواطع ولوحات توزيع للمقاولين", title_en: "Breakers and boards for contractors", title_ur: "ٹھیکیداروں کے لیے بریکرز اور بورڈز", subtitle_ar: "MCB وRCCB ولوحات 12 و24 خط متوفرة في المخزون.", subtitle_en: "MCBs, RCCBs and 12 / 24-way boards in stock.", subtitle_ur: "ایم سی بی، آر سی سی بی اور 12 / 24 وے بورڈز اسٹاک میں دستیاب۔", cta_ar: "تسوّق القواطع", cta_en: "Shop breakers", cta_ur: "بریکرز خریدیں", link: "/c/breakers", sort: 1 },
  { placement: "promo", title_ar: "إنارة LED توفّر في فاتورة الكهرباء", title_en: "LED lighting that cuts the power bill", title_ur: "ایل ای ڈی لائٹس جو بجلی کا بل کم کریں", subtitle_ar: "لمبات وسبوتات وكشافات بضمان حتى سنتين.", subtitle_en: "Bulbs, downlights and flood lights with up to 2 years warranty.", subtitle_ur: "بلب، ڈاؤن لائٹس اور فلڈ لائٹس دو سال تک وارنٹی کے ساتھ۔", cta_ar: "تسوّق الإنارة", cta_en: "Shop lighting", cta_ur: "لائٹس خریدیں", link: "/c/led-lights", sort: 2 },
];

export const FAQS: [qa: string, qe: string, qu: string, aa: string, ae: string, au: string][] = [
  ["هل الأسعار تشمل ضريبة القيمة المضافة؟", "Do prices include VAT?", "کیا قیمتوں میں VAT شامل ہے؟",
    "نعم، جميع الأسعار المعروضة في المتجر تشمل ضريبة القيمة المضافة 15%، وتظهر قيمة الضريبة مفصّلة في سلة التسوق وفي الفاتورة الضريبية.",
    "Yes. All prices shown in the store include 15% VAT. The VAT amount is itemised in your cart and on the tax invoice.",
    "جی ہاں۔ اسٹور میں دکھائی گئی تمام قیمتوں میں 15٪ VAT شامل ہے، اور ٹیکس کی رقم کارٹ اور ٹیکس انوائس میں الگ دکھائی جاتی ہے۔"],
  ["ما هي مدة التوصيل؟", "How long does delivery take?", "ڈیلیوری میں کتنا وقت لگتا ہے؟",
    "يستغرق التوصيل العادي من يومين إلى خمسة أيام عمل حسب المدينة، والتوصيل السريع من يوم إلى يومين للمدن الرئيسية. يظهر موعد التوصيل المتوقع عند إتمام الطلب.",
    "Standard delivery takes 2–5 working days depending on the city; express delivery takes 1–2 working days to major cities. The expected delivery window is shown at checkout.",
    "عام ڈیلیوری شہر کے لحاظ سے 2 سے 5 کاروباری دن لیتی ہے، اور ایکسپریس ڈیلیوری بڑے شہروں میں 1 سے 2 دن۔ متوقع تاریخ چیک آؤٹ پر دکھائی جاتی ہے۔"],
  ["ما هي طرق الدفع المتاحة؟", "Which payment methods do you accept?", "ادائیگی کے کون سے طریقے دستیاب ہیں؟",
    "تظهر طرق الدفع المتاحة لطلبك في خطوة الدفع، وتشمل الدفع عند الاستلام، والدفع الإلكتروني ببطاقة مدى والبطاقات الائتمانية وApple Pay وSTC Pay متى كان مفعّلًا.",
    "The payment methods available for your order are shown at the payment step: cash on delivery, and online payment by mada, credit card, Apple Pay and STC Pay where enabled.",
    "آپ کے آرڈر کے لیے دستیاب طریقے ادائیگی کے مرحلے پر دکھائے جاتے ہیں: کیش آن ڈیلیوری، اور جہاں فعال ہو وہاں مدیٰ، کریڈٹ کارڈ، Apple Pay اور STC Pay۔"],
  ["هل يمكنني إرجاع المنتج؟", "Can I return a product?", "کیا میں پروڈکٹ واپس کر سکتا ہوں؟",
    "نعم، يمكنك طلب الإرجاع خلال 7 أيام من الاستلام بشرط أن يكون المنتج بحالته الأصلية وغير مستخدم وفي عبوته. قدّم الطلب من صفحة الطلب في حسابك.",
    "Yes. You can request a return within 7 days of delivery, provided the product is unused, in its original condition and packaging. Start the request from the order page.",
    "جی ہاں۔ وصولی کے 7 دن کے اندر واپسی کی درخواست دی جا سکتی ہے، بشرطیکہ پروڈکٹ غیر استعمال شدہ اور اصل پیکنگ میں ہو۔ درخواست آرڈر کے صفحے سے دیں۔"],
  ["هل أحصل على فاتورة ضريبية؟", "Will I receive a tax invoice?", "کیا مجھے ٹیکس انوائس ملے گی؟",
    "نعم، تصدر فاتورة ضريبية إلكترونية لكل طلب وتتضمن رمز الاستجابة السريعة. وللمنشآت يمكن إدخال الرقم الضريبي عند إتمام الطلب لإصدار فاتورة ضريبية باسم المنشأة.",
    "Yes. An electronic tax invoice with a QR code is issued for every order. Businesses can enter their VAT number at checkout to receive a tax invoice in the company name.",
    "جی ہاں۔ ہر آرڈر کے لیے QR کوڈ کے ساتھ الیکٹرانک ٹیکس انوائس جاری ہوتی ہے۔ ادارے چیک آؤٹ پر اپنا VAT نمبر درج کر کے کمپنی کے نام پر انوائس حاصل کر سکتے ہیں۔"],
  ["هل المنتجات عليها ضمان؟", "Are products covered by warranty?", "کیا مصنوعات پر وارنٹی ہے؟",
    "مدة الضمان مذكورة في صفحة كل منتج. يغطي الضمان عيوب التصنيع ولا يشمل سوء الاستخدام أو التركيب الخاطئ.",
    "The warranty period is stated on each product page. It covers manufacturing defects and does not cover misuse or incorrect installation.",
    "وارنٹی کی مدت ہر پروڈکٹ کے صفحے پر درج ہے۔ یہ مینوفیکچرنگ نقائص کا احاطہ کرتی ہے، غلط استعمال یا غلط تنصیب کا نہیں۔"],
];
